version: '3.1'

services:
  
  webServer:
    image: tfso:tag
    build: 
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - '8080:8080'
    volumes: 
      - ./application_layer/src/:/webServer/application_layer/src/:website
      - ./application_layer/server.js:/webServer/application_layer/server.js:website
      - ./presentation_layer/:/webServer/presentation_layer/:website
      
  mongo:
    image: mongo
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: "loliadmin"
    #  MONGO_INITDB_ROOT_PASSWORD: "loliadmin"
    ports:
      - '27017:27017'
    volumes:
      - ./data_layer/:/data/db/

  garage:
    image: dxflrs/garage:v1.0.0
    restart: always
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./data_layer/S3/meta:/var/lib/garage/meta
      - ./data_layer/S3/data:/var/lib/garage/data