version: '3.1'

services:
  
  backend:
    image: applayer:tag
    build: 
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - '8080:8080'
    volumes: 
      - ./backend/:/backend/:website
      - /backend/node_modules
      - /backend/dist
    environment:
      - JWT_SECRET='secretxd'
      - MONGO_URL='mongodb://0.0.0.0:27017'

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data_layer/:/data/db/

  garage:
    image: dxflrs/garage:v1.0.0
    restart: always
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./data_layer/S3/meta:/var/lib/garage/meta
      - ./data_layer/S3/data:/var/lib/garage/data