version: '3.1'

services:
  
  webServer:
    image: tfso:tag
    build: 
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - '8080:8080'
    volumes: 
      - ./presentation_layer:/webServer/presentation_layer:website
      - ./application_layer:/webServer/application_layer:website

  mongo:
    image: mongo
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: "loliadmin"
    #  MONGO_INITDB_ROOT_PASSWORD: "loliadmin"
    ports:
      - '27017:27017'
    volumes:
      - ./data_layer/:/data/db/