version: '3.1'

services:
  
  appLayer:
    image: applayer:tag
    build: 
      context: .
      dockerfile: DockerfileApp
    restart: 'always'
    ports:
      - '8080:8080'
    volumes: 
      - ./application_layer/:/webServer/application_layer/:website
      - /node_modules/
      - /dist/
    environment:
      - JWT_SECRET='secretxd'

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data_layer/:/data/db/

  garage:
    image: dxflrs/garage:v1.0.0
    restart: always
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./data_layer/S3/meta:/var/lib/garage/meta
      - ./data_layer/S3/data:/var/lib/garage/data